### PR TITLE
In Sha256Pipe, fail the passed deferred if the input stream fails

### LINKED ISSUE #17: Sha256Pipe fails to complete Deferred if input stream fails
In [`Sha256Pipe`](https://github.com/Dwolla/fs2-aws/blob/02a48b8ff591a1e8f158aa3666b8d66f5ff7cb41/core/jvm/src/main/scala/com/dwolla/fs2utils/hashing/Sha256Pipe.scala#L9-L33), if the input stream fails, the passed `promisedHexString: Deferred[F, String]` will never be completed. This is unexpected, since the hash will never be available if the input is incomplete.

### PR DESCRIPTION
**Pull request by bpholt**
Fixes #17

### CODE REVIEW

File: core/jvm/src/main/scala/com/dwolla/fs2utils/hashing/Sha256Pipe.scala [hunk 1]
```diff
@@ -7,7 +7,7 @@ import cats.effect.concurrent.Deferred
 import fs2._
 
 object Sha256Pipe {
-  def apply[F[_] : Sync](promisedHexString: Deferred[F, String]): Pipe[F, Byte, Byte] = {
+  def apply[F[_] : Sync](promisedHexString: Deferred[F, Either[Throwable, String]]): Pipe[F, Byte, Byte] = {
```
Comment (bpholt) [inline core/jvm/src/main/scala/com/dwolla/fs2utils/hashing/Sha256Pipe.scala:10]: `Deferred[F, *]`s [do not have an error channel](https://gitter.im/typelevel/cats-effect?at=605121e8823b6654d2af3646), even if the underlying `F[_]` does, so the output type needs to carry the possibility of error.

**Review by coreyjonoliver — APPROVED** [review]
